services:
  react-project-dev:
    container_name: react-project-container
    image: react-project-dev-image
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
      # - /frontend/node_modules
    command: npm run start-watch